// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package qyweixinsso.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.core.Core;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.IUser;
import java.util.logging.Logger;
import java.util.logging.*;

public class SSO_SetSession extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String WecomUserName;

	public SSO_SetSession(IContext context, java.lang.String WecomUserName)
	{
		super(context);
		this.WecomUserName = WecomUserName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        IContext ctx = getContext();
        IUser user = Core.getUser(ctx, this.WecomUserName);
        if (user != null) {
            try {
                ISession session = Core.initializeSession(user, null);
                // get the response object
                if (ctx.getRuntimeResponse().isPresent()) {
                    IMxRuntimeResponse res = ctx.getRuntimeResponse().get();
                    setCookies(res, session); // set xassessionid and xasid cookies
                    return true;
                }
            } catch (Exception e) {
                Logger log = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);
                log.log(Level.INFO, e.toString());
                return false;
            }

        }
        return false;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SSO_SetSession";
	}

	// BEGIN EXTRA CODE
    private void setCookies(IMxRuntimeResponse response, ISession session) {
        response.addCookie("XASSESSIONID", session.getId().toString(), "/", "", -1, true);
        response.addCookie("XASID", "0." + Core.getXASId(), "/", "", -1, true);
    }
	// END EXTRA CODE
}
